[package]
name = "rust-runtime-speed-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.release]
strip = true
# opt-level = "z" # Optimize for size
opt-level = 3 # Optimize for speed
